## Pandas Dataframes

In [1]:
import pandas as pd

In [4]:
data={
    'Name':["Hamim","Fahim","Tasin"],
    'Age':[21,13,15],
    'Class':["1st year","5th","9th"]
}

df = pd.DataFrame(data)
df

    Name  Age     Class
0  Hamim   21  1st year
1  Fahim   13       5th
2  Tasin   15       9th

#### Selection and Indexing Columns

In [14]:
print(df["Age"][0]) # Selectng single column data
print('\n')
print(df[["Name","Class"]])  # Selectng Multiple column data

21


    Name     Class
0  Hamim  1st year
1  Fahim       5th
2  Tasin       9th

#### Creating New Column

In [ ]:
df["Result"]=["A","A+","A-"]
df["Study-hour"]=[2,5,2]

df

    Name  Age     Class Result  Study-hour
0  Hamim   21  1st year      A           2
1  Fahim   13       5th     A+           5
2  Tasin   15       9th     A-           2

#### Removing

In [24]:
df.drop("Class",axis=1)

    Name  Age Result
0  Hamim   21      A
1  Fahim   13     A+
2  Tasin   15     A-

#### Selecting rows

In [ ]:
print(df.loc[0])
print("\n")
print(df.loc[[0,1]][["Name","Age"]]),,
print("\n")
print(df.iloc[2])

Name         Hamim
Age             21
Class     1st year
Result           A
Name: 0, dtype: object


    Name  Age
0  Hamim   21
1  Fahim   13


Name      Tasin
Age          15
Class       9th
Result       A-
Name: 2, dtype: object

#### Conditional Selection

In [30]:
df

    Name  Age     Class Result
0  Hamim   21  1st year      A
1  Fahim   13       5th     A+
2  Tasin   15       9th     A-

In [32]:
df[(df["Age"] < 20) & (df["Result"] == "A+") ]

    Name  Age Class Result
1  Fahim   13   5th     A+

### Missing Data

In [34]:

import numpy as np
import pandas as pd


data = {
    "Employee_ID": [
        1001, 1002, 1003, 1004,
        1005, 1006, 1007, 1008,
        1009, 1010, 1011, 1012
    ],

    "Name": [
        "Rahim", "Karim", np.nan, "Sultana",
        "Jamil", np.nan, "Akram", "Fahima",
        "Nabila", "Hasan", np.nan, "Sakib"
    ],

    "Department": [
        "IT", "HR", "Sales", np.nan,
        "IT", "Finance", np.nan, "Marketing",
        "HR", "IT", "Sales", np.nan
    ],

    "Salary": [
        85000, np.nan, 60000, 55000,
        np.nan, 70000, 95000, 62000,
        58000, np.nan, 75000, 68000
    ],

    "Age": [
        25, 30, 28, np.nan,
        35, 32, 27, 29,
        np.nan, 26, 31, 24
    ],

    "Join_Date": [
        "2021-01-15", "2022-03-20", np.nan,
        "2020-11-05", "2023-05-12", np.nan,
        "2019-08-25", "2022-01-10",
        "2021-07-18", "2024-02-01",
        np.nan, "2023-09-15"
    ]
}

df = pd.DataFrame(data)

print(df)

    Employee_ID     Name Department   Salary   Age   Join_Date
0          1001    Rahim         IT  85000.0  25.0  2021-01-15
1          1002    Karim         HR      NaN  30.0  2022-03-20
2          1003      NaN      Sales  60000.0  28.0         NaN
3          1004  Sultana        NaN  55000.0   NaN  2020-11-05
4          1005    Jamil         IT      NaN  35.0  2023-05-12
5          1006      NaN    Finance  70000.0  32.0         NaN
6          1007    Akram        NaN  95000.0  27.0  2019-08-25
7          1008   Fahima  Marketing  62000.0  29.0  2022-01-10
8          1009   Nabila         HR  58000.0   NaN  2021-07-18
9          1010    Hasan         IT      NaN  26.0  2024-02-01
10         1011      NaN      Sales  75000.0  31.0         NaN
11         1012    Sakib        NaN  68000.0  24.0  2023-09-15

In [37]:
df.isna()

    Employee_ID   Name  Department  Salary    Age  Join_Date
0         False  False       False   False  False      False
1         False  False       False    True  False      False
2         False   True       False   False  False       True
3         False  False        True   False   True      False
4         False  False       False    True  False      False
5         False   True       False   False  False       True
6         False  False        True   False  False      False
7         False  False       False   False  False      False
8         False  False       False   False   True      False
9         False  False       False    True  False      False
10        False   True       False   False  False       True
11        False  False        True   False  False      False

In [38]:
df.isna().sum()

Employee_ID    0
Name           3
Department     3
Salary         3
Age            2
Join_Date      3
dtype: int64

In [39]:
df.isna().any()

Employee_ID    False
Name            True
Department      True
Salary          True
Age             True
Join_Date       True
dtype: bool

#### Removing missing data

In [42]:
df.dropna() # removing nan rows

   Employee_ID    Name Department   Salary   Age   Join_Date
0         1001   Rahim         IT  85000.0  25.0  2021-01-15
7         1008  Fahima  Marketing  62000.0  29.0  2022-01-10

In [43]:
df

    Employee_ID     Name Department   Salary   Age   Join_Date
0          1001    Rahim         IT  85000.0  25.0  2021-01-15
1          1002    Karim         HR      NaN  30.0  2022-03-20
2          1003      NaN      Sales  60000.0  28.0         NaN
3          1004  Sultana        NaN  55000.0   NaN  2020-11-05
4          1005    Jamil         IT      NaN  35.0  2023-05-12
5          1006      NaN    Finance  70000.0  32.0         NaN
6          1007    Akram        NaN  95000.0  27.0  2019-08-25
7          1008   Fahima  Marketing  62000.0  29.0  2022-01-10
8          1009   Nabila         HR  58000.0   NaN  2021-07-18
9          1010    Hasan         IT      NaN  26.0  2024-02-01
10         1011      NaN      Sales  75000.0  31.0         NaN
11         1012    Sakib        NaN  68000.0  24.0  2023-09-15

In [47]:
df.dropna(thresh=5)

    Employee_ID    Name Department   Salary   Age   Join_Date
0          1001   Rahim         IT  85000.0  25.0  2021-01-15
1          1002   Karim         HR      NaN  30.0  2022-03-20
4          1005   Jamil         IT      NaN  35.0  2023-05-12
6          1007   Akram        NaN  95000.0  27.0  2019-08-25
7          1008  Fahima  Marketing  62000.0  29.0  2022-01-10
8          1009  Nabila         HR  58000.0   NaN  2021-07-18
9          1010   Hasan         IT      NaN  26.0  2024-02-01
11         1012   Sakib        NaN  68000.0  24.0  2023-09-15

#### Filling Missing Data

In [48]:
df

    Employee_ID     Name Department   Salary   Age   Join_Date
0          1001    Rahim         IT  85000.0  25.0  2021-01-15
1          1002    Karim         HR      NaN  30.0  2022-03-20
2          1003      NaN      Sales  60000.0  28.0         NaN
3          1004  Sultana        NaN  55000.0   NaN  2020-11-05
4          1005    Jamil         IT      NaN  35.0  2023-05-12
5          1006      NaN    Finance  70000.0  32.0         NaN
6          1007    Akram        NaN  95000.0  27.0  2019-08-25
7          1008   Fahima  Marketing  62000.0  29.0  2022-01-10
8          1009   Nabila         HR  58000.0   NaN  2021-07-18
9          1010    Hasan         IT      NaN  26.0  2024-02-01
10         1011      NaN      Sales  75000.0  31.0         NaN
11         1012    Sakib        NaN  68000.0  24.0  2023-09-15

In [53]:
df.fillna(0)

    Employee_ID     Name Department   Salary   Age   Join_Date
0          1001    Rahim         IT  85000.0  25.0  2021-01-15
1          1002    Karim         HR      0.0  30.0  2022-03-20
2          1003        0      Sales  60000.0  28.0           0
3          1004  Sultana          0  55000.0   0.0  2020-11-05
4          1005    Jamil         IT      0.0  35.0  2023-05-12
5          1006        0    Finance  70000.0  32.0           0
6          1007    Akram          0  95000.0  27.0  2019-08-25
7          1008   Fahima  Marketing  62000.0  29.0  2022-01-10
8          1009   Nabila         HR  58000.0   0.0  2021-07-18
9          1010    Hasan         IT      0.0  26.0  2024-02-01
10         1011        0      Sales  75000.0  31.0           0
11         1012    Sakib          0  68000.0  24.0  2023-09-15

In [54]:
salary_value=df["Salary"].mean()
values={"Salary":salary_value}

df.fillna(value=values)

    Employee_ID     Name Department        Salary   Age   Join_Date
0          1001    Rahim         IT  85000.000000  25.0  2021-01-15
1          1002    Karim         HR  69777.777778  30.0  2022-03-20
2          1003      NaN      Sales  60000.000000  28.0         NaN
3          1004  Sultana        NaN  55000.000000   NaN  2020-11-05
4          1005    Jamil         IT  69777.777778  35.0  2023-05-12
5          1006      NaN    Finance  70000.000000  32.0         NaN
6          1007    Akram        NaN  95000.000000  27.0  2019-08-25
7          1008   Fahima  Marketing  62000.000000  29.0  2022-01-10
8          1009   Nabila         HR  58000.000000   NaN  2021-07-18
9          1010    Hasan         IT  69777.777778  26.0  2024-02-01
10         1011      NaN      Sales  75000.000000  31.0         NaN
11         1012    Sakib        NaN  68000.000000  24.0  2023-09-15